MAKEFOLDER := ../.make
include $(MAKEFOLDER)/util.mk
include ../project.mk

CFLAGS += -I .

SRCFOLDER := .
SRC := core/qfib.cpp

LIB := libqfib.a

include $(MAKEFOLDER)/defaults.mk
include $(MAKEFOLDER)/lib.mk
